#

name: hatch-bump
description: Bumps hatch projects in CI

inputs:
  type:
    description: "Type of the hatch version bump"
    type: string
    default: "dev"
    required: false
  ref:
    description: ""
    type: string
    default: ""
    required: false
  force:
    description: "Force push the version bump"
    type: boolean
    default: false
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
    - ${{ inputs.ref }}
    - ${{ inputs.force }}

