#

name: hatch-bump
description: Bumps hatch projects in CI
author: phdenzel
branding:
  icon: arrow-up-circle
  color: gray-dark

inputs:
  type:
    description: "Type of the hatch version bump"
    type: string
    default: "dev"
    required: false
  ref:
    description: ""
    type: string
    default: ""
    required: false
  github-token:
    description: "GitHub or personal access token"
    default: ${{ github.token }}
    required: false
  force:
    description: "Force push (with lease) the version bump"
    type: boolean
    default: false
    required: false
  tag:
    description: "Tag the new commit"
    type: boolean
    default: true
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.type }}
    - ${{ inputs.ref }}
    - ${{ inputs.github-token }}
    - ${{ inputs.force }}
    - ${{ inputs.tag }}
